//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Role;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group_members")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub group_id: u64,
    pub user_id: u64,
    pub role: Option<Role>,
    pub joined_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pulse_group::Entity",
        from = "Column::GroupId",
        to = "super::pulse_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PulseGroup,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::pulse_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PulseGroup.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
