
database:
  url: "43.139.97.119:3306/pulse_chat"
  username: root
  password: ******************
  max_connections: 100
  min_connections: 10
  connect_timeout: 10
  idle_timeout: 60
  max_lifetime: 60
  sqlx_logging: true

token:
  secret: "dev_12356"

public_list:
  - "/api/user/login"
  - "/api/user/register"